### ISSUE TITLE
Get rid of the "SlackNotifications" directory

### ISSUE THREAD

**Issue by miken32** [kulttuuri/SlackNotifications#27]
Having your code in a subdirectory makes it impossible to clone the repo and use it directly from Mediawiki. The repo should be named "SlackNotifications" and the files should be in the root directory!

Alternatively, you could make all the path references in your code relative instead of hard-coded against `$IP/extensions`.

**Comment by kulttuuri** [comment]
You're right! I renamed the repository to be the same name as the extension so this can be directly cloned into your mediawiki extensions folder and moved everything to top level :)
