### ISSUE TITLE
Suggested javascript encode \ in the curl post

### ISSUE THREAD

**Issue by actiondannz** [kulttuuri/SlackNotifications#29]
Excellent work on this guys. One suggestion / fix which worked for us.

With the JSON preparation not using a library there is room for some encoding issues which apparently I am the first to experience this one...

On our system, running on windows, we use windows authentication, so user names are of the format _domain\bob_ and the **\** caused slack to return _invalid_payload_ error (which are not handled by the extension - not complaining).

So with _domain\bob_ in javascript the _\b_ is not a valid escape character and that is where the error is, so below this on line ~372:

`$message = str_replace('"', "'", $message);`

We added this:

```
//Ensure a random \ is not read as the beginning of an escape character. Windows users may be authenticated with a username containing domain\user, so to ensure \ is encoded as \\...
$message = str_replace('\\', "\\\\", $message);
```

**Comment by kulttuuri** [comment]
Implemented! Better late than never. Thanks! :)
