### ISSUE TITLE
Allow users to invoke a MediaWiki page from within Slack

### ISSUE THREAD

**Issue by teolemon** [kulttuuri/SlackNotifications#33]
Allow users to invoke a MediaWiki page from within Slack. 
Example: it reads the message content (What's the API rate limit), and looks it up on the MediaWiki install. It then returns a list of candidates that can be replied back to the Slack user.

**Comment by kulttuuri** [comment]
Thanks for the idea suggestion, that bot service would be handy! :) However this is out of scope for this project, as that would be bot service for Slack, not extension for MediaWiki which this project currently is. Ideally, this would be it's own project with separate codebase in GitHub.
