### ISSUE TITLE
Notification came in html format

### ISSUE THREAD

**Issue by brunopenso** [kulttuuri/SlackNotifications#38]
Hy Guys,

I just connect the extension with our slack channel and all the notification are coming as it should.

But the way the message is shown on the screen is very bad. See below. Am I missing some configuration? Maybe on slack?

`
<index.php?title=User:emailOfTheUser|emailOfTheUser> has edited article <index.php?title=Main_Page|Main Page> (<index.php?title=Main_Page&action=edit|edit> | <index.php?title=Main_Page&action=delete|delete> | <index.php?title=Main_Page&action=history|history> | <index.php?title=Main_Page&diff=prev&oldid=10|diff>)\n  (+0 bytes)
`

**Comment by brunopenso** [comment]
I also tried with wgSlackSendMethod to file_get_contents and get the same result

**Comment by kulttuuri** [comment]
Looks like you are missing this configuration as there is no server prepended or we are for some stripping the server out:
$wgSlackNotificationWikiUrl		= "http://your_wiki_url/";

**Comment by brunopenso** [comment]
Hi I`m using this

// URL into your MediaWiki installation with the trailing /.
$wgSlackWikiUrl		= "http://myUrl/";


Should I use wgSlackWikiUrl or wgSlackNotificationWikiUrl? Maybe both?

**Comment by brunopenso** [comment]
It worked here. The problem is the official docs on the link https://www.mediawiki.org/wiki/Extension:SlackNotifications

I think the best option is to remove the sample code from the mediawiki page and redirect it to this repo.

Thoughts?

**Comment by kulttuuri** [comment]
Ah! Sorry about this - we just recently renamed all these variables to have have "Slack" on all of them to distinct them from variables used in other extensions. We forgot to rename those variables on the MediaWiki page.

I will now update the page! :) For now I think we can get away just by making that change as this should not happen again, this was just a one time change that was required to make.
